version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8
      - image: ndidplatform/tendermint:latest
        environment:
          TM_RPC_PORT: 45000
        command:
          - genesis
          - --p2p.laddr=tcp://0.0.0.0:47000
          - --rpc.laddr=tcp://0.0.0.0:45000
          - --proxy_app=tcp://localhost:46000
      - image: ndidplatform/abci:latest
        command: ["tcp://0.0.0.0:46000"]
    steps:
      - checkout
      - run: sleep 25
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run:
          name: Install node modules
          command: |
            npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: Set up Development Key
          command: |
            TENDERMINT_IP=localhost \
            TENDERMINT_PORT=45000 \
            NODE_ID=ndid1 \
            npm run initDevKey

      - run:
          name: Start service
          command: |
            MQ_CONTACT_IP=localhost \
            MQ_BINDING_PORT=5555 \
            ROLE=ndid \
            NODE_ID=ndid1 \
            npm start
          background: true
      - run:
          name: Start sample testing
          command: |
            sleep 15
            curl -v http://localhost:8080/utility/namespaces
            curl -v http://localhost:8080/utility/idp
            curl -v http://localhost:8080/utility/services

