version: '3'
services:
  api-ndid-master:
    image: ndidplatform/api:latest
    environment:
      - ROLE=ndid
      - NODE_ID=ndid1
      - NDID_IP=api-ndid-master
      - TENDERMINT_IP=tm-ndid
      - TENDERMINT_PORT=${TM_RPC_PORT:-45000}
      - DB_IP=api-redis
      - SERVER_PORT=${API_PORT:-8080}
      - NDID_NODE=true
      - IS_MASTER=true
    security_opt:
      - no-new-privileges
    ports:
      - "8080:${API_PORT:-8080}"
    networks:
      - ndidplatform
    volumes:
      - ./keys/ndid/:/api/keys/
      - ./data/ndid/:/api/main-server/data/
  #api-ndid-worker:
  #  image: ndidplatform/api:latest
  #  environment:
  #    - MASTER_SERVER_IP=api-ndid-master
  #    - DB_IP=api-redis
  #  security_opt:
  #    - no-new-privileges
  #  networks:
  #    - ndidplatform
  api-idp-1-master:
    image: ndidplatform/api:latest
    environment:
      - ROLE=idp
      - NODE_ID=idp1
      - NDID_IP=api-ndid-master
      - TENDERMINT_IP=tm-idp
      - TENDERMINT_PORT=${TM_RPC_PORT:-45000}
      - MQ_CONTACT_IP=mq-idp-1
      - MQ_BINDING_PORT=${MQ_PORT:-5555}
      - MQ_SERVICE_SERVER_IP=mq-idp-1
      - DB_IP=api-redis
      - SERVER_PORT=${API_PORT:-8080}
      - IS_MASTER=true
    security_opt:
      - no-new-privileges
    ports:
      - "8100:${API_PORT:-8080}"
    networks:
      - ndidplatform
    volumes:
      - ./keys/idp-1/:/api/keys/
      - ./data/idp-1/:/api/main-server/data/
  api-idp-1-worker:
    image: ndidplatform/api:latest
    environment:
      - NODE_ID=idp1
      - MASTER_SERVER_IP=api-idp-1-master
      - DB_IP=api-redis
      - TENDERMINT_IP=tm-idp
      - TENDERMINT_PORT=${TM_RPC_PORT:-45000}
    security_opt:
      - no-new-privileges
    networks:
      - ndidplatform
    volumes:
      - ./keys/idp-1/:/api/keys/
      - ./data/idp-1/:/api/main-server/data/
  #api-idp-2-master:
  #  image: ndidplatform/api:latest
  #  environment:
  #    - ROLE=idp
  #    - NODE_ID=idp2
  #    - NDID_IP=api-ndid-master
  #    - TENDERMINT_IP=tm-idp
  #    - TENDERMINT_PORT=${TM_RPC_PORT:-45000}
  #    - MQ_CONTACT_IP=mq-idp-2
  #    - MQ_BINDING_PORT=${MQ_PORT:-5555}
  #    - MQ_SERVICE_SERVER_IP=mq-idp-2
  #    - DB_IP=api-redis
  #    - SERVER_PORT=${API_PORT:-8080}
  #    - IS_MASTER=true
  #  security_opt:
  #    - no-new-privileges
  #  ports:
  #    - "8101:${API_PORT:-8080}"
  #  networks:
  #    - ndidplatform
  #api-idp-2-worker:
  #  image: ndidplatform/api:latest
  #  environment:
  #    - NODE_ID=idp2
  #    - MASTER_SERVER_IP=api-idp-2-master
  #    - DB_IP=api-redis
  #    - TENDERMINT_IP=tm-idp
  #    - TENDERMINT_PORT=${TM_RPC_PORT:-45000}
  #    - MQ_SERVICE_SERVER_IP=mq-idp-2
  #  security_opt:
  #    - no-new-privileges
  #  networks:
  #    - ndidplatform
  api-rp-master:
    image: ndidplatform/api:latest
    environment:
      - ROLE=rp
      - NODE_ID=rp1
      - NDID_IP=api-ndid-master
      - TENDERMINT_IP=tm-rp
      - TENDERMINT_PORT=${TM_RPC_PORT:-45000}
      - MQ_CONTACT_IP=mq-rp
      - MQ_BINDING_PORT=${MQ_PORT:-5555}
      - MQ_SERVICE_SERVER_IP=mq-rp
      - DB_IP=api-redis
      - SERVER_PORT=${API_PORT:-8080}
      - IS_MASTER=true
    security_opt:
      - no-new-privileges
    ports:
      - "8200:${API_PORT:-8080}"
    networks:
      - ndidplatform
    volumes:
      - ./keys/rp/:/api/keys/
      - ./data/rp/:/api/main-server/data/
  api-rp-worker:
    image: ndidplatform/api:latest
    environment:
      - NODE_ID=rp1
      - MASTER_SERVER_IP=api-rp-master
      - DB_IP=api-redis
      - TENDERMINT_IP=tm-rp
      - TENDERMINT_PORT=${TM_RPC_PORT:-45000}
    security_opt:
      - no-new-privileges
    networks:
      - ndidplatform
    volumes:
      - ./keys/rp/:/api/keys/
      - ./data/rp/:/api/main-server/data/
  api-as-master:
    image: ndidplatform/api:latest
    environment:
      - ROLE=as
      - NODE_ID=as1
      - NDID_IP=api-ndid-master
      - TENDERMINT_IP=tm-as
      - TENDERMINT_PORT=${TM_RPC_PORT:-45000}
      - MQ_CONTACT_IP=mq-as
      - MQ_BINDING_PORT=${MQ_PORT:-5555}
      - MQ_SERVICE_SERVER_IP=mq-as
      - DB_IP=api-redis
      - SERVER_PORT=${API_PORT:-8080}
      - IS_MASTER=true
    security_opt:
      - no-new-privileges
    ports:
      - "8300:${API_PORT:-8080}"
    networks:
      - ndidplatform
    volumes:
      - ./keys/as/:/api/keys/
      - ./data/as/:/api/main-server/data/
  api-as-worker:
    image: ndidplatform/api:latest
    environment:
      - NODE_ID=as1
      - MASTER_SERVER_IP=api-as-master
      - DB_IP=api-redis
      - TENDERMINT_IP=tm-as
      - TENDERMINT_PORT=${TM_RPC_PORT:-45000}
    security_opt:
      - no-new-privileges
    networks:
      - ndidplatform
    volumes:
      - ./keys/as/:/api/keys/
      - ./data/as/:/api/main-server/data/
  api-redis:
    image: redis:4-alpine
    security_opt:
      - no-new-privileges
    networks:
      - ndidplatform

  # MQ service server containers
  mq-idp-1:
    image: ndidplatform/mq:latest
    environment: 
      - NODE_ID=idp1
      - MQ_BINDING_PORT=${MQ_PORT:-5555}
      - SERVER_PORT=${MQ_SERVER_PORT:-50051}
    security_opt:
      - no-new-privileges
    networks:
      - ndidplatform
    ulimits:
      nofile: 
        soft: 30000
        hard: 30000
  mq-idp-2:
    image: ndidplatform/mq:latest
    environment: 
      - NODE_ID=idp2
      - MQ_BINDING_PORT=${MQ_PORT:-5555}
      - SERVER_PORT=${MQ_SERVER_PORT:-50051}
    security_opt:
      - no-new-privileges
    networks:
      - ndidplatform
    ulimits:
      nofile: 
        soft: 30000
        hard: 30000
  mq-rp:
    image: ndidplatform/mq:latest
    environment: 
      - NODE_ID=rp1
      - MQ_BINDING_PORT=${MQ_PORT:-5555}
      - SERVER_PORT=${MQ_SERVER_PORT:-50051}
    security_opt:
      - no-new-privileges
    networks:
      - ndidplatform
    ulimits:
      nofile: 
        soft: 30000
        hard: 30000
  mq-as:
    image: ndidplatform/mq:latest
    environment: 
      - NODE_ID=as1
      - MQ_BINDING_PORT=${MQ_PORT:-5555}
      - SERVER_PORT=${MQ_SERVER_PORT:-50051}
    security_opt:
      - no-new-privileges
    networks:
      - ndidplatform
    ulimits:
      nofile: 
        soft: 30000
        hard: 30000
      
networks:
  ndidplatform:
